user_management/config/routes.rb
Rails.application.routes.draw do

  get "/user/new" => "users#new", as: :user_new
  post "/user/new" => "users#create", as: :user_create
  get "/users/list" => "users#index", as: :users_list
  get "/user/:id/edit" => "users#edit", as: :user_edit
  put "/user/:id/edit" => "users#update", as: :user_update
  get "/user/:id" => "users#show", as: :user_show
  delete "/user/:id" => "users#destroy", as: :user_destroy

  get "/project/new" => "projects#new", as: :project_new
  post "/project/new" => "projects#create", as: :project_create
  get "/projects/list" => "projects#index", as: :projects_list
  get "/project/:id" => "projects#show", as: :project_show

end

user_management/app/models/project.rb
class Project < ActiveRecord::Base
	has_and_belongs_to_many :users
end

user_management/app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :projects
	attr_accessor :password
	before_save :encrypt_password
	validates_presence_of :firstname, message: "Enter first name"
	validates_presence_of :lastname, message: "Enter last name"
	validates :password,  format: { with: /\A^(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$\Z/, message: "Password Should contain 1 Uppercase, 1 Number, 1 Special Character and should be of minimum 8 Characters."}
	validates_presence_of :email, message: "Email cannot be empty"
	validates_uniqueness_of :email

	def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end

  end
end

user_management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

user_management/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@project=Project.new
	end
	def create
		@project=Project.new(user_params)
		
	end
	def index
		@projects=Project.all
	end
	def show
		@project=Project.find_by_id(params[:id])
	end
	private
	def user_params
		params.require(:project).permit(:name,:duration,:teamsize,:cost,:domain)
	end
end

user_management/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user=User.new
	end
	def create
		@user=User.new(user_params)
		if @user.save
			redirect_to users_list_path
		  else
		    render 'new'
		  end

		
	end
	def index
		@users=User.all
	end
	def edit
		@user=User.find_by_id(params[:id])

	end
	def update
		@user=User.find_by_id(params[:id])
		@user.update_attributes(user_params)
		redirect_to users_list_path
	end
	def show
		@user=User.find_by_id(params[:id])
	end
	def destroy
		@user=User.find_by_id(params[:id])
		@user.destroy
		redirect_to users_list_path
	end
	private
	def user_params
		params.require(:user).permit(:firstname,:lastname,:email,:password)
	end
end

user_management/app/helpers/application_helper.rb
module ApplicationHelper
	def show_errors(object, field_name)
  if object.errors.any?
    # if !object.errors.messages[field_name].blank?
      object.errors.messages[field_name].join(", ")
    
  end
end 
end

user_management/app/helpers/projects_helper.rb
module ProjectsHelper
end

user_management/app/helpers/users_helper.rb
module UsersHelper
end

user_management/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

user_management/app/views/projects/index.html.erb
<body style="background-color:powderblue">
<center>
<h1>Listing all projects</h1>
<table  border="solid ">
	<tr>
		<th>Name</th>
		<th>Duration</th>
		<th>Teamsize</th>
		<th>Cost</th>
		<th>Domain</th>

	</tr>
	<% @projects.each do |project| %>
	<tr>
		<td><%= project.name %></td>
		<td><%= project.duration %></td>
		<td><%= project.teamsize %></td>
		<td><%= project.cost %></td>
		<td><%= project.domain %></td>

		
	</tr>
	<% end %>
</table>
</center>
</body>

user_management/app/views/projects/new.html.erb
<body >
<center>
<h1>New project Creation</h1>

<div >

<%= form_for :project do |f| %>

<div >
  
<p >
	<%= f.label :name %><br>
	<%= f.text_field :name %> 
	
</p>
<p >
	<%= f.label :duration %><br>
	<%= f.text_field :duration %>

</p>
<p >
	<%= f.label :teamsize %><br>
	<%= f.text_field :teamsize %>

</p>
<p >
	<%= f.label :cost %><br>
	<%= f.text_field :cost %>


</p>
<p >
	<%= f.label :domain %><br>
	<%= f.text_field :domain %>


</p>
<p>
	<%= f.submit %>
</p>
</div>
<% end %>
</div>
</center>
</body>

user_management/app/views/projects/show.html.erb
<body >
<center>
<h1>Listing all projects</h1>
<table  border="solid ">
	<tr>
		<th>Name</th>
		<th>Duration</th>
		<th>Teamsize</th>
		<th>Cost</th>
		<th>Domain</th>

	</tr>
	
	<tr>
		<td><%= @project.name %></td>
		<td><%= @project.duration %></td>
		<td><%= @project.teamsize %></td>
		<td><%= @project.cost %></td>
		<td><%= @project.domain %></td>
	
		
	</tr>

</table>
</center>
</body>

user_management/app/views/users/edit.html.erb
<body style="background-color:skyblue">
<center>
<h1>Edit page</h1>
<%= form_for :user,url: user_edit_path(@user), method: :put do |f| %>
<p>
	<%= f.label :first_name %><br>
	<%= f.text_field :firstname %>
</p>
<p>
	<%= f.label :last_name %><br>
	<%= f.text_field :lastname %>
</p>
<p>
	<%= f.label :email %><br>
	<%= f.text_field :email %>
</p>
<p>
	<%= f.label :password %><br>
	<%= f.password_field :password %>

</p>
<p>
	<%= f.submit %>
</p>
<% end %>
</center>
</body>

user_management/app/views/users/index.html.erb
<body style="background-color:powderblue">
<center>
<h1>Listing all users</h1>
<table  border="solid ">
	<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email</th>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td><%= user.firstname %></td>
		<td><%= user.lastname %></td>
		<td><%= user.email %></td>
		<td><%= link_to "profile", user_show_path(user)%> </td>
		
		<td><%= link_to "Edit", user_edit_path(user)%> </td>
		<td><%= link_to "Destroy", user_destroy_path(user), method: :delete, data: {
		confirm: "Are you sure?"
		}%> </td>
	</tr>
	<% end %>
</table>
</center>
</body>

user_management/app/views/users/new.html.erb
<body style="background-color:powderblue">
<center>
<h1>New user Creation</h1>

<div >

<%= form_for :user do |f| %>

<div >
  
<p class='error'>
	<%= f.label :first_name %><br>
	<%= f.text_field :firstname %> 
  <%= show_errors(@user, :firstname) %>
	
</p>
<p class='error'>
	<%= f.label :last_name %><br>
	<%= f.text_field :lastname %>
  <%= show_errors(@user, :lastname) %>

</p>
<p class='error'>
	<%= f.label :email %><br>
	<%= f.email_field :email %>
  <%= show_errors(@user, :email) %>

</p>
<p >
	<%= f.label :password %><br>
	<%= f.password_field :password %>
 <%= show_errors(@user, :password) %>


</p>
<p>
	<%= f.submit %>
</p>
</div>
<% end %>
</div>
</center>
</body>

user_management/app/views/users/show.html.erb
<body style="background-color:lightgreen">
<center>
<h1>Listing user</h1>
<table border="solid">
	<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email</th>
	</tr>
	<tr>
		<td><%= @user.firstname %></td>
		<td><%= @user.lastname %></td>
		<td><%= @user.email %></td>
	

	<td><%= link_to "Edit", user_edit_path(@user)%> </td>
		<td><%= link_to "Destroy", user_destroy_path(@user), method: :delete, data: {
		confirm: "Are you sure?"
		}%> </td>

	</tr>

</table>
</center>
</body>